/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.5.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as deskChatbot from "../deskChatbot";
import type * as desks from "../desks";
import type * as environment from "../environment";
import type * as helpers from "../helpers";
import type * as http from "../http";
import type * as ingest_load from "../ingest/load";
import type * as messages from "../messages";
import type * as seed from "../seed";
import type * as serve from "../serve";
import type * as sessions from "../sessions";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  deskChatbot: typeof deskChatbot;
  desks: typeof desks;
  environment: typeof environment;
  helpers: typeof helpers;
  http: typeof http;
  "ingest/load": typeof ingest_load;
  messages: typeof messages;
  seed: typeof seed;
  serve: typeof serve;
  sessions: typeof sessions;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
